<?php
$config = require __DIR__ . '/config.php';
require __DIR__ . '/site_layout.php';
site_start($config, 'About Boss Lady Perfumery', 'Meet Boss Lady Perfumery, fragrance for women who own the room.', 'about');
?>
<section class="page-hero"><div class="site-wrap page-hero-inner reveal"><div class="eyebrow">Our signature</div><h1>For the woman<br><em>who arrives.</em></h1><p>Boss Lady Perfumery is a fragrance house built around confidence, presence, and the quiet power of being unforgettable.</p></div></section>
<section class="page-section"><div class="site-wrap story-grid"><div class="story-image reveal" role="img" aria-label="Boss Lady Perfumery packaging"></div><div class="story-copy reveal"><div class="eyebrow">The Boss Lady note</div><h2>Luxury is how you feel in it.</h2><p>We believe fragrance is more than a finishing touch. It is the first hello, the memory left behind, and the ritual that changes how you carry yourself through the day.</p><p>Our fragrances are chosen for the woman who chooses confidence on purpose: something warm for a slow morning, something magnetic for a night out, and something unmistakably hers for every day in between.</p><div class="story-list"><div><strong>Curated with intention</strong><span>Scents selected for character, not clutter.</span></div><div><strong>Personal by design</strong><span>Real guidance when you are choosing your signature.</span></div><div><strong>Made to be remembered</strong><span>Fragrance moments worth coming back to.</span></div></div><a class="site-button site-button-dark" href="/shop">Explore our fragrances ↗</a></div></div></section>
<section class="page-section" style="background:var(--rose-light);padding-top:70px;padding-bottom:70px"><div class="site-wrap"><div class="section-heading reveal"><h2>A little more than perfume.</h2><p>The details matter. From the first message to the final delivery, we keep the experience personal.</p></div><div class="site-grid"><article class="site-card reveal"><div class="eyebrow">01</div><h3>Presence</h3><p>A signature scent changes the way you enter a room. We curate for that feeling.</p></article><article class="site-card reveal"><div class="eyebrow">02</div><h3>Guidance</h3><p>Not sure what fits? Talk to a real person on WhatsApp and find your direction.</p></article><article class="site-card reveal"><div class="eyebrow">03</div><h3>Ritual</h3><p>Make the everyday feel considered. Your fragrance is the moment you keep for yourself.</p></article></div></div></section>
<section class="page-section"><div class="site-wrap" style="text-align:center"><div class="eyebrow reveal">Ready when you are</div><h2 class="reveal" style="margin:17px auto 25px;max-width:700px;font:400 clamp(38px,5vw,60px)/1 var(--serif)">Find the version of you that lingers.</h2><a class="site-button site-button-rose reveal" href="<?=site_support_url($config, 'Hello Boss Lady Perfumery, I would love a fragrance recommendation.')?>">Ask for a recommendation ↗</a></div></section>
<?php site_end($config); ?>
