<?php
require __DIR__ . '/admin_common.php';
require __DIR__ . '/admin_layout.php';
$statusLabels = ['new' => 'New', 'processing' => 'Processing', 'ready' => 'Ready for delivery', 'shipped' => 'Shipped', 'delivered' => 'Delivered', 'cancelled' => 'Cancelled'];
$paymentLabels = ['awaiting_whatsapp' => 'Awaiting WhatsApp confirmation', 'pending' => 'Payment pending', 'paid' => 'Paid', 'failed' => 'Payment failed', 'refunded' => 'Refunded'];
$statusCounts = array_fill_keys($allowedStatuses, 0);
$paymentCounts = array_fill_keys($allowedPaymentStatuses, 0);
foreach ($orders as $order) {
    if (isset($statusCounts[$order['order_status']])) $statusCounts[$order['order_status']]++;
    if (isset($paymentCounts[$order['payment_status']])) $paymentCounts[$order['payment_status']]++;
}
admin_start('Insights', 'insights', $config);
?>
<section><div class="overview-head"><div><div class="eyebrow">Store intelligence</div><h2>See what needs attention.</h2></div><p>A quick view of product visibility, stock, fulfilment, and payment signals.</p></div><div class="metrics"><div class="metric"><small>Live products</small><strong><?=$activeProducts?></strong><span>Customer-facing</span></div><div class="metric"><small>Low stock</small><strong><?=$stockAlerts?></strong><span>Three or fewer left</span></div><div class="metric"><small>Open orders</small><strong><?=$openOrders?></strong><span>Not completed</span></div><div class="metric"><small>Paid revenue</small><strong>₦<?=number_format($paidTotal / 100, 0)?></strong><span>Recorded orders</span></div></div></section>
<section class="panel"><div class="section-title"><div><div class="eyebrow">Fulfilment</div><h2>Order pipeline.</h2></div><p>Move each order forward as you confirm payment and delivery.</p></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:8px"><?php foreach ($allowedStatuses as $status): ?><div style="padding:14px 10px;background:#f7f0eb;text-align:center"><strong style="display:block;font:24px Georgia;color:var(--ink)"><?=$statusCounts[$status]?></strong><span style="display:block;margin-top:6px;color:var(--muted);font-size:10px;line-height:1.35;text-transform:uppercase;letter-spacing:.08em"><?=admin_h($statusLabels[$status] ?? 'Updated')?></span></div><?php endforeach; ?></div></section>
<section class="panel"><div class="section-title"><div><div class="eyebrow">Payment</div><h2>Payment signals.</h2></div><p>Payment is confirmed separately from fulfilment.</p></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:8px"><?php foreach ($allowedPaymentStatuses as $status): ?><div style="padding:14px 10px;border:1px solid var(--line);text-align:center"><strong style="display:block;font:22px Georgia;color:var(--ink)"><?=$paymentCounts[$status]?></strong><span style="display:block;margin-top:6px;color:var(--muted);font-size:10px;line-height:1.35;text-transform:uppercase;letter-spacing:.05em"><?=admin_h($paymentLabels[$status] ?? 'Payment update')?></span></div><?php endforeach; ?></div></section>
<section class="panel"><div class="section-title"><div><div class="eyebrow">Recent activity</div><h2>Latest orders.</h2></div><a class="dashboard-link" href="/admin/orders">Open full order desk ↗</a></div><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr style="text-align:left;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.08em"><th style="padding:10px;border-bottom:1px solid var(--line)">Order</th><th style="padding:10px;border-bottom:1px solid var(--line)">Customer</th><th style="padding:10px;border-bottom:1px solid var(--line)">Status</th><th style="padding:10px;border-bottom:1px solid var(--line)">Total</th></tr></thead><tbody><?php foreach (array_slice($orders, 0, 8) as $order): ?><tr><td style="padding:13px 10px;border-bottom:1px solid var(--line)"><a class="dashboard-link" href="<?=admin_h(rtrim($config['site_url'], '/') . '/order/' . $order['order_token'])?>" target="_blank" rel="noreferrer"><?=admin_h($order['order_code'])?></a></td><td style="padding:13px 10px;border-bottom:1px solid var(--line)"><?=admin_h($order['customer_name'])?></td><td style="padding:13px 10px;border-bottom:1px solid var(--line)"><?=admin_h($statusLabels[$order['order_status']] ?? 'Updated')?></td><td style="padding:13px 10px;border-bottom:1px solid var(--line)">₦<?=number_format($order['total_kobo'] / 100, 2)?></td></tr><?php endforeach; ?><?php if (!$orders): ?><tr><td colspan="4" style="padding:20px 10px;color:var(--muted)">No orders yet.</td></tr><?php endif; ?></tbody></table></div></section>
<?php admin_end(); ?>
