<?php
require __DIR__ . '/admin_common.php';
require __DIR__ . '/admin_layout.php';
admin_start('Overview', 'overview', $config);
?>
<section id="overview"><div class="overview-head"><div><div class="eyebrow">Store pulse</div><h2>Everything in one place.</h2></div><p>Manage the collection, keep an eye on orders, and stay close to every customer conversation.</p></div><div class="metrics"><div class="metric"><small>Live products</small><strong><?=$activeProducts?></strong><span>Visible to customers</span></div><div class="metric"><small>Hidden products</small><strong><?=$hiddenProducts?></strong><span>Can return to Live</span></div><div class="metric"><small>Archived forever</small><strong><?=$archivedProducts?></strong><span>History only</span></div><div class="metric"><small>Open orders</small><strong><?=$openOrders?></strong><span>Need attention</span></div><div class="metric"><small>Awaiting payment</small><strong><?=$awaitingPayment?></strong><span>Confirm on WhatsApp</span></div><div class="metric"><small>Paid revenue</small><strong>₦<?=number_format($paidTotal / 100, 0)?></strong><span>Recorded orders</span></div></div></section>
<section class="panel"><div class="section-title"><div><div class="eyebrow">Quick actions</div><h2>Keep the day moving.</h2></div><p>Shortcuts for the work you do most.</p></div><div class="quick-grid"><a class="quick-card" href="/admin/products"><span>✦</span><strong>Add or edit products</strong><small>Update the collection, images, stock, and visibility.</small></a><a class="quick-card" href="/admin/orders"><span>◌</span><strong>Review orders</strong><small>Update fulfilment and payment.</small></a><a class="quick-card" href="/admin/archive"><span>▣</span><strong>Open permanent archive</strong><small>Review products retired from the catalogue.</small></a></div></section>
<section class="panel"><div class="section-title"><div><div class="eyebrow">Attention needed</div><h2>Small checks, better service.</h2></div></div><div class="overview-note"><div><strong><?=$stockAlerts?> low-stock item<?= $stockAlerts === 1 ? '' : 's' ?></strong><p>Review products with three or fewer units left before promoting them.</p><a class="dashboard-link" href="/admin/products?view=live">Review live products ↗</a></div><div><strong><?=$awaitingPayment?> payment<?= $awaitingPayment === 1 ? '' : 's' ?> to confirm</strong><p>Keep payment status separate from fulfilment so every customer gets a clear update.</p><a class="dashboard-link" href="/admin/orders">Open order desk ↗</a></div><div><strong><?=$archivedProducts?> permanent archive<?= $archivedProducts === 1 ? '' : 's' ?></strong><p>Use Hidden for temporary pauses. Archive only products that should never return to Live.</p><a class="dashboard-link" href="/admin/archive">View archive ↗</a></div></div></section>
<?php admin_end(); ?>
