<?php
require __DIR__ . '/admin_common.php';
require __DIR__ . '/admin_layout.php';
admin_start('Overview', 'overview', $config);
?>
<section id="overview"><div class="overview-head"><div><div class="eyebrow">Store pulse</div><h2>Everything in one place.</h2></div><p>Manage the collection, keep an eye on orders, and stay close to every customer conversation.</p></div><div class="metrics"><div class="metric"><small>Active products</small><strong><?=$activeProducts?></strong><span>In the collection</span></div><div class="metric"><small>Open orders</small><strong><?=$openOrders?></strong><span>Need attention</span></div><div class="metric"><small>Awaiting payment</small><strong><?=$awaitingPayment?></strong><span>Confirm on WhatsApp</span></div><div class="metric"><small>Paid revenue</small><strong>₦<?=number_format($paidTotal / 100, 0)?></strong><span>Recorded orders</span></div></div></section>
<section class="panel"><div class="section-title"><div><div class="eyebrow">Quick actions</div><h2>Keep the day moving.</h2></div><p>Shortcuts for the work you do most.</p></div><div class="quick-grid"><a class="quick-card" href="/admin/products"><span>✦</span><strong>Add or edit products</strong><small>Update the collection and images.</small></a><a class="quick-card" href="/admin/orders"><span>◌</span><strong>Review orders</strong><small>Update fulfilment and payment.</small></a><a class="quick-card" href="/admin/settings"><span>⚙</span><strong>Workspace settings</strong><small>Change your password securely.</small></a></div></section>
<section class="panel"><div class="section-title"><div><div class="eyebrow">What is next</div><h2>Run the storefront with confidence.</h2></div></div><div class="overview-note"><div><strong>Products</strong><p>Upload clean product photography and keep stock accurate so customers see what is actually available.</p></div><div><strong>Orders</strong><p>Set payment to Paid only after confirming it, then move the fulfilment status as the order travels.</p></div><div><strong>Customer care</strong><p>Use the pre-filled Support link whenever a customer needs a recommendation or order update.</p></div></div></section>
<?php admin_end(); ?>
