<?php
$config = require __DIR__ . '/config.php';
require __DIR__ . '/site_layout.php';
site_start($config, 'FAQs | Boss Lady Perfumery', 'Answers to common Boss Lady Perfumery ordering, payment, and delivery questions.', '');
?>
<style>
.faq-list{max-width:820px;margin:0 auto}.faq-list details{border-top:1px solid var(--line);padding:22px 0}.faq-list details:last-child{border-bottom:1px solid var(--line)}.faq-list summary{display:flex;justify-content:space-between;gap:20px;cursor:pointer;list-style:none;font:400 23px var(--serif)}.faq-list summary::-webkit-details-marker{display:none}.faq-list summary:after{content:'+';color:var(--gold);font:24px Arial}.faq-list details[open] summary:after{content:'−'}.faq-list details p{max-width:690px;margin:14px 35px 0 0;color:var(--muted);font-size:13px;line-height:1.8}.faq-cta{margin-top:70px;padding:45px;background:var(--ink);color:var(--cream);text-align:center}.faq-cta h2{margin:0 auto 17px;max-width:580px;font:400 clamp(34px,5vw,52px)/1 var(--serif)}.faq-cta p{max-width:480px;margin:0 auto 23px;color:#b9acad;font-size:13px;line-height:1.7}
</style>
<section class="page-hero"><div class="site-wrap page-hero-inner reveal"><div class="eyebrow">Helpful answers</div><h1>Good questions deserve<br><em>clear answers.</em></h1><p>Everything you need to order with confidence. If you still need help, our WhatsApp concierge is ready.</p></div></section>
<section class="page-section"><div class="site-wrap faq-list reveal"><details open><summary>How do I place an order?</summary><p>Choose a fragrance, add it to your bag, enter your delivery details, and select Continue to WhatsApp. We confirm availability, payment, and delivery with you personally.</p></details><details><summary>Do you take payment on the website?</summary><p>No. Your order is created on the website, but payment details are confirmed directly with Boss Lady Perfumery on WhatsApp. Do not pay an account or number that has not been confirmed by us.</p></details><details><summary>How will I receive my order update?</summary><p>After checkout, you receive an Order ID. Use the Track an order page with the same phone number used at checkout, or open the private order link sent to you.</p></details><details><summary>Can I ask for a fragrance recommendation?</summary><p>Yes. Use the Scent Finder or message us on WhatsApp. Tell us who the fragrance is for, when it will be worn, and the kind of feeling you want.</p></details><details><summary>Can I change or cancel an order?</summary><p>Contact us as soon as possible on WhatsApp. We will do our best to help before the order has been prepared or dispatched.</p></details><details><summary>What if I have another question?</summary><p>Our support team can help with product details, delivery, and order updates. <a class="text-link" href="<?=site_support_url($config, 'Hello Boss Lady Perfumery, I have a question.')?>">Message us on WhatsApp ↗</a></p></details></div><div class="site-wrap faq-cta reveal"><h2>Still deciding?</h2><p>A real conversation is often the quickest way to find the right fragrance.</p><a class="site-button site-button-rose" href="<?=site_support_url($config, 'Hello Boss Lady Perfumery, I would like help choosing a fragrance.')?>">Talk to a scent concierge ↗</a></div></section>
<?php site_end($config); ?>
