<?php
$config = require __DIR__ . '/config.php';
require __DIR__ . '/site_layout.php';
site_start($config, 'Find your fragrance | Boss Lady Perfumery', 'Find a Boss Lady Perfumery fragrance with a personal WhatsApp consultation.', 'finder');
?>
<style>
.finder-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:55px;align-items:start}.finder-copy h2{margin:18px 0;font:400 clamp(38px,5vw,60px)/.98 var(--serif);letter-spacing:-.04em}.finder-copy p{max-width:440px;color:var(--muted);font-size:14px;line-height:1.8}.finder-note{margin-top:30px;padding:20px;border-left:2px solid var(--gold);background:var(--rose-light);color:var(--muted);font-size:12px;line-height:1.7}.finder-card{padding:32px;background:var(--ink);color:var(--cream);box-shadow:0 24px 55px #3b22231c}.finder-card h2{margin:0 0 7px;font:400 32px var(--serif)}.finder-card>p{margin-bottom:24px;color:#b9acad;font-size:12px}.finder-question{margin:0 0 22px;padding:0;border:0}.finder-question legend{margin-bottom:10px;color:var(--rose);font-size:11px;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.finder-question label{display:flex;align-items:center;gap:10px;margin:8px 0;color:#e8dede;font-size:13px;letter-spacing:0;text-transform:none}.finder-question input{width:auto;accent-color:var(--rose)}.finder-submit{width:100%;border:0}.finder-result{margin-top:18px;padding:15px;background:#302629;color:#ddd0d0;font-size:12px;line-height:1.7}.finder-result a{color:var(--rose);font-weight:700;text-decoration:underline;text-underline-offset:4px}@media(max-width:850px){.finder-grid{grid-template-columns:1fr;gap:30px}}
</style>
<section class="page-hero"><div class="site-wrap page-hero-inner reveal"><div class="eyebrow">Scent finder</div><h1>Find the fragrance<br><em>that feels like you.</em></h1><p>Answer three simple questions and start a personal fragrance conversation with Boss Lady on WhatsApp.</p></div></section>
<section class="page-section"><div class="site-wrap finder-grid"><div class="finder-copy reveal"><div class="eyebrow">A more personal way to choose</div><h2>Your signature starts with a feeling.</h2><p>There is no wrong answer. Tell us the moment you are dressing for, the mood you want to carry, and how noticeable you want your fragrance to be.</p><div class="finder-note"><strong>What happens next?</strong><br>Your answers open a ready-to-send WhatsApp message. We will guide you toward the fragrance that suits you best.</div></div><div class="finder-card reveal"><h2>Tell us what you want.</h2><p>Your answers are used only to start your recommendation.</p><form id="finderForm"><fieldset class="finder-question"><legend>01. When will you wear it?</legend><label><input type="radio" name="occasion" value="everyday" required> Every day</label><label><input type="radio" name="occasion" value="evening"> An evening or date</label><label><input type="radio" name="occasion" value="gift"> A thoughtful gift</label></fieldset><fieldset class="finder-question"><legend>02. How should it feel?</legend><label><input type="radio" name="mood" value="soft and floral" required> Soft and floral</label><label><input type="radio" name="mood" value="warm and sensual"> Warm and sensual</label><label><input type="radio" name="mood" value="bold and memorable"> Bold and memorable</label></fieldset><fieldset class="finder-question"><legend>03. How noticeable should it be?</legend><label><input type="radio" name="strength" value="soft" required> Soft and close</label><label><input type="radio" name="strength" value="balanced"> Balanced and easy</label><label><input type="radio" name="strength" value="noticeable"> Noticeable and lasting</label></fieldset><button class="site-button site-button-rose finder-submit" type="submit">Get my recommendation ↗</button></form><div class="finder-result" id="finderResult" hidden></div></div></div></section>
<script>
document.querySelector('#finderForm').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget),message='Hello Boss Lady Perfumery, I would like a fragrance recommendation. Occasion: '+form.get('occasion')+'. Mood: '+form.get('mood')+'. Strength: '+form.get('strength')+'.';const url='https://wa.me/<?=htmlspecialchars($config['whatsapp'], ENT_QUOTES, 'UTF-8')?>?text='+encodeURIComponent(message),result=document.querySelector('#finderResult');result.hidden=false;result.innerHTML='Your recommendation is ready. <a href="'+url+'" target="_blank" rel="noreferrer">Continue on WhatsApp ↗</a>'});
</script>
<?php site_end($config); ?>
