<?php
$config = require __DIR__ . '/config.php';
require __DIR__ . '/site_layout.php';
site_start($config, 'Track your order | Boss Lady Perfumery', 'Track a Boss Lady Perfumery order with your order ID and phone number.', 'track');
?>
<section class="page-hero"><div class="site-wrap page-hero-inner reveal"><div class="eyebrow">Order care</div><h1>Your order,<br><em>in view.</em></h1><p>Use the order ID and phone number from checkout to see your latest status. Need a hand? Our WhatsApp concierge is one tap away.</p></div></section>
<section class="page-section"><div class="site-wrap track-panel"><div class="reveal"><div class="eyebrow">Simple by design</div><h2 style="margin:18px 0;font:400 clamp(38px,5vw,60px)/.98 var(--serif);letter-spacing:-.04em">Stay close to your scent story.</h2><p style="max-width:430px;color:var(--muted);font-size:14px;line-height:1.8">Your order status is updated by Boss Lady as it moves from new, to processing, to ready for delivery. Payment details are confirmed personally on WhatsApp.</p><a class="site-button site-button-outline" style="margin-top:18px;background:var(--ink);color:var(--cream)" href="<?=site_support_url($config, 'Hello Boss Lady Perfumery, I need help tracking my order.')?>">Ask for help ↗</a></div><div class="track-form-card reveal"><h2>Track an order.</h2><p>Enter the exact details used at checkout.</p><form class="track-form" id="trackForm"><label for="trackCode">Order ID</label><input id="trackCode" placeholder="BL-20260823-ABCDEF1234567890" autocomplete="off" required><label for="trackPhone">Phone / WhatsApp</label><input id="trackPhone" placeholder="Phone number" autocomplete="tel" required><button class="site-button site-button-rose" type="submit">Show order status ↗</button></form><div id="trackResult" aria-live="polite"></div></div></div></section>
<script>
function trackEscape(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function trackMoney(value){return '₦'+(Number(value)/100).toLocaleString('en-NG',{minimumFractionDigits:2})}document.querySelector('#trackForm').addEventListener('submit',async event=>{event.preventDefault();const box=document.querySelector('#trackResult'),code=document.querySelector('#trackCode').value.trim(),phone=document.querySelector('#trackPhone').value.trim();box.innerHTML='<p style="color:#b9acad;font-size:12px">Checking your order...</p>';try{const response=await fetch('/api/track-order.php?code='+encodeURIComponent(code)+'&phone='+encodeURIComponent(phone),{headers:{Accept:'application/json'}}),result=await response.json();if(!result.ok){box.innerHTML='<div class="status" style="margin-top:18px">Order not found. Check the ID and phone number, then try again.</div>';return}const order=result.order;box.innerHTML=`<div class="status" style="margin-top:18px"><strong>${trackEscape(order.order_code)}</strong><br>Order: ${trackEscape(order.order_status)} · Payment: ${trackEscape(order.payment_status)}<br>Total: ${trackMoney(order.total_kobo)} · Updated: ${trackEscape(order.updated_at)}</div>`}catch(_){box.innerHTML='<div class="status" style="margin-top:18px">Could not connect to the store. Please try again.</div>'}});
</script>
<?php site_end($config); ?>
